
["YUNG's Better Dungeons"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Dungeons".General]
		# 是否开启地牢在生成时会生成骷髅头颅或者其他怪物头颅。
		# 该选项对于整合包作者来说也许有用。
		# 默认：true
		#
		"Enable Skulls & Heads" = true
		# 有的地牢可能会生成下界方块，例如：灵魂沙、灵魂营火、灵魂灯笼。
		# 注：地牢生成的下界方块不会包括远古残骸这种影响平衡的方块，地牢生成的方块是纯装饰的。
		# 如果要让地牢禁止生成下界方块，请将该选项设置为false。
		# 该选项对于整合包作者来说也许有用。
		# 默认：true
		#
		"Enable Nether Blocks in Dungeons" = true

	###########################################################################################################
	## 僵尸地牢设置
	###########################################################################################################
	["YUNG's Better Dungeons"."Zombie Dungeons"]
		# 僵尸地牢在生成时会生成一个楼梯，该楼梯会连接到地表，该选项是设置楼梯的长度。
		# 不建议将数值设置太大，因为可能会有BUG。
		# 默认：20
		#
		"Zombie Dungeon Surface Entrance Staircase Max Length" = 20

	###########################################################################################################
	## 小型地牢设置
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Dungeons"]
		# 设置在小型地牢中旗帜的生成数量上限。
		# 默认：2
		# 范围：0 ~ 8
		"Small Dungeon Max Banner Count" = 2
		# 设置在小型地牢中最少会生成多少个地牢宝箱。
		# 默认：1
		"Small Dungeon Min Chest Count" = 1
		# 设置在小型地牢中最多会生成多少个地牢宝箱。
		# 默认：2
		"Small Dungeon Max Chest Count" = 2
		# 小型地牢在生成时是否会生成矿物方块。
		# 如果要禁用地牢中的矿物方块，请将该选项设置为false，禁用生成后会在原本的矿物方块位置上使用空气方块替换掉矿物方块。
		# 默认：true
		#
		"Allow Ore Blocks in Corners" = true

	###########################################################################################################
	## 小型下界地牢设置
	## 以下选项默认禁用
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Nether Dungeons"]
		# 是否生成小型下界地牢。
		# 默认：false
		"Enable Small Nether Dungeons" = false
		# 在小型下界地牢中生成的凋灵骷髅是否会掉落凋灵骷髅头颅。
		# 默认：true
		"Wither Skeletons From Spawners Drop Wither Skeleton Skulls" = true
		# 在小型下界地牢中生成的烈焰人是否会掉落烈焰棒。
		# 默认：true
		"Blazes From Spawners Drop Blaze Rods" = true
		# 在小型地牢中生成的最多旗帜数量。
		# 默认：2
		# 范围：0 ~ 8
		"Small Nether Dungeon Max Banner Count" = 2

