
["YUNG's Better Strongholds"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Strongholds".General]
		# 设置蜘蛛网在末地要塞普通结构中的生成概率。
		# 默认：0.1
		"Cobweb Spawn Rate (NORMAL)" = 0.1
		# 设置蜘蛛网在末地要塞的图书馆结构中的蜘蛛刷怪笼旁的生成概率。
		# 默认：0.3
		"Cobweb Spawn Rate (SPAWNER)" = 0.3
		# 设置在末地要塞里能够生成火把的概率。
		# 默认：0.1
		"Torch Spawn Rate" = 0.1
		# 设置在末地要塞里能够生成灯笼的概率。
		# 默认：0.2
		"Lantern Spawn Rate" = 0.2

