
["YUNG's Better Witch Huts"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Witch Huts".General]
		# 是否禁止原版的沼泽小屋的生成。
		# 默认：true
		#
		"Disable Vanilla Witch Huts" = true

