
["YUNG's Better Ocean Monuments"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Ocean Monuments".General]
		# 是否禁止原版的海洋神殿的生成。
		# 默认：true
		#
		"Disable Vanilla Ocean Monuments" = true

