#“命中标记”模式的可配置选项：OFF、KILL、HIT_AND_KILL
hitMarkerMode = "HIT_AND_KILL"
killSoundEnabled = true

#有的枪械拥有“爆发开火”的开火模式，单次可以连续发射多颗子弹。
#在该选项中你可以调整所有与“爆发开火”有关的配置。
[burstfire]
	#是否开启枪械的“爆发开火”开火模式。
	enable = true
	#每次发射的子最多弹数量。
	#范围：1 ~ ∞
	shotsPerBurst = 3

#设置枪械的“装填弹药”模式以及弹药的其他内容。
[reload]
	#是否允许枪械在工作台中合成后自带对应枪械的空弹匣。
	gunComeEmptyMag = true
	#设置枪械的额外装填弹药时间，该选项会在对应枪械的基础装填弹药时间上再额外加上一些时间，单位是Tick。
	#范围：0 ~ 200
	duration = 0
	#当枪械内的弹药为空时自动销毁弹匣而不是在重新装填弹药时将空弹匣返还给玩家。
	destroyMagWhenEmpty = false

#设置配件的各种内容。
[scope]
	#玩家是否可以为枪械安装配件。
	#在关闭该选项之前如果枪械里已经存在了配件，那么在关闭后配件不会消失。
	attachmentsAllowed = true
	#设置额外的放大倍率（乘法），例如：八倍镜的放大倍率是8x，如果将该选项设置为3.0，那么八倍镜最后可以放大高达24倍。
	#范围：0.1 ~ 3.0
	zoomMultiplier = 1.0

#设置爆头伤害以及其属性。
[headshot]
	#是否开启爆头的伤害加成。
	enabled = true
	#当子弹命中头部时，伤害加成的比例（乘法），例如：M4A1突击步枪的基础伤害为7点，那么爆头伤害将为28点，爆头算法是基础伤害 x 本选项数值。
	#范围：1.0 ~ 10.0
	bonusDamage = 4.0

#设置背刺伤害以及其属性。
[backstab]
	#是否开启背刺的伤害加成。
	enabled = false
	#当使用近战武器从背部攻击时的伤害加成比例。（乘法）
	#范围：1.0 ~ 10.0
	bonusDamage = 1.2

#设置暴击伤害以及其属性。
[criticalHit]
	#是否开启暴击的伤害加成。
	enabled = false
	#暴击时的伤害加成比例。（乘法）
	#范围：1.0 ~ 10.0
	bonusDamage = 1.0
	#玩家能造成暴击的概率。（百分比）
	#范围：0.0 ~ 1.0
	chance = 0.005

#设置近战武器的伤害和耐久的属性。
[damageDropOff]
	#是否开启当耐久降低时自动降低武器的伤害。
	enable = false
	#每降低1点耐久时会降低多少伤害。（百分比）
	#范围：0.01 ~ 100.0
	loss = 0.1
	#当耐久降低后最多会降低近战武器的多少伤害。
	#范围：0.0 ~ 20.0
	minimumDamage = 2.0

#设置投掷物与世界互动的内容。
[explosives]
	#是否允许玩家使用遥控起爆器来引爆一定范围内的爆炸物。
	#该选项不会影响玩家通过合成的方式获得，只会关闭起爆器的远程起爆的功能。
	remoteDetonatorEnabled = true
	#是否允许使用C4炸弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了C4炸弹的功能。
	C4Enabled = true
	#是否允许使用诱饵弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了诱饵弹的功能。
	decoyGrenadeEnabled = true
	#是否允许使用燃烧弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了燃烧弹的功能。
	fireGrenadeEnabled = true
	#是否允许使用闪光弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了闪光弹的功能。
	flashGrenadeEnabled = true
	#是否允许使用破片手榴弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了破片手榴弹的功能。
	fragGrenadeEnabled = true
	#是否允许使用烟雾弹。
	#该选项不会影响玩家通过合成的方式获得，只是关闭了烟雾弹的功能。
	smokeGrenadeEnabled = true
	#设置C4炸弹的爆炸与方块的交互方式。
	#NONE：无互动，方块无变化。
	#BREAK：方块会被破坏并且会在爆炸后变成掉落物。
	#DESTROY：方块会被破坏并且不会产生掉落物，只会留下一个弹坑。
	#可设置的选项：NONE、BREAK、DESTROY
	c4ExplosionMode = "NONE"
	#设置燃烧弹的爆炸与方块的交互方式。
	#NONE：无互动，方块无变化。
	#BREAK：方块会被破坏并且会在爆炸后变成掉落物。
	#DESTROY：方块会被破坏并且不会产生掉落物，只会留下一个弹坑。
	#可设置的选项：NONE、BREAK、DESTROY
	fireGrenadeExplosionMode = "NONE"
	#设置破片手榴弹的爆炸与方块的交互方式。
	#NONE：无互动，方块无变化。
	#BREAK：方块会被破坏并且会在爆炸后变成掉落物。
	#DESTROY：方块会被破坏并且不会产生掉落物，只会留下一个弹坑。
	#可设置的选项：NONE、BREAK、DESTROY
	fragGrenadeExplosionMode = "NONE"
	#设置遥控起爆器的有效范围，单位是块。
	#范围：1.0 ~ 500.0
	remoteDetonatorRange = 50.0
	#设置C4炸弹的爆炸半径，单位是块。
	#范围：0.1 ~ 50.0
	c4Radius = 4.0
	#设置燃烧弹的爆炸半径，单位是块。
	#范围：0.1 ~ 50.0
	fireGrenadeRadius = 2.0
	#设置闪光弹的闪光半径，单位是块。
	#范围：0.1 ~ 200.0
	flashGrenadeRadius = 50.0
	#设置破片手榴弹的爆炸半径，单位是块。
	#范围：0.1 ~ 50.0
	fragGrenadeRadius = 4.0
	#设置烟雾弹的烟雾半径，单位是块。
	#范围：0.1 ~ 5.0
	smokeGrenadeRadius = 1.0
	#设置C4炸弹的爆炸击退距离。（乘法）
	#范围：0.0 ~ 30.0
	c4KnockbackMultiplier = 1.0
	#设置燃烧弹的爆炸击退距离。（乘法）
	#范围：0.0 ~ 30.0
	fireGrenadeKnockbackMultiplier = 1.0
	#设置破片手榴弹的爆炸击退距离。（乘法）
	#范围：0.0 ~ 30.0
	fragGrenadeKnockbackMultiplier = 1.0
	#设置C4炸弹的基础爆炸伤害。（乘法）
	#范围：0.0 ~ 30.0
	c4DamageMultiplier = 1.0
	#设置燃烧弹的基础爆炸伤害。（乘法）
	#范围：0.0 ~ 30.0
	fireGrenadeDamageMultiplier = 1.0
	#设置破片手榴弹的基础爆炸伤害。（乘法）
	#范围：0.0 ~ 30.0
	fragGrenadeDamageMultiplier = 1.0
	#设置闪光弹在生效之前需要等待的时间，单位是Tick。
	#范围：0 ~ 18000
	flashGrenadeTicksBeforeActivation = 30
	#设置破片手榴弹在生效之前需要等待的时间，单位是Tick。
	#范围：0 ~ 18000
	fragGrenadeTicksBeforeActivation = 35
	#设置诱饵弹的持续时间，单位是Tick。
	#范围：0 ~ 18000
	decoyGrenadeTicksBeforeDeactivation = 400
	#设置闪光弹的持续时间，单位是Tick。
	#范围：0 ~ 18000
	flashGrenadeTicksBeforeDeactivation = 5
	#设置烟雾弹的持续时间，单位是Tick。
	#范围：0 ~ 18000
	smokeGrenadeTicksBeforeDeactivation = 500
	#发射器是否可以发射投掷物。（例如：闪光弹、烟雾弹等）
	dispenseGrenades = true

