
["Better Caves"]
	# 设置“洞穴优化”模组生效维度的白名单，如果开启了全局白名单则该白名单会被忽略。
	# 维度列表必须使用逗号隔开，使用方括号圈起来。
	# 并且维度列表必须包括模组的命名空间。
	# 例如："[minecraft:overworld, minecraft:the_nether, rats:ratlantis]" （原版的主世界，原版的下界，老鼠模组的鼠西洲）
	# 默认："[minecraft:overworld]"
	"Whitelisted Dimensions" = "[minecraft:overworld]"
	# 将“洞穴优化”模组设置为在每个维度都会生效。
	# 如果启用了该功能，那么上面的白名单选项将会被忽略。
	# 默认：false
	"Enable Global Whitelist" = false

	###########################################################################################################
	## 设置洞穴、岩洞、峡谷等内容的参数
	###########################################################################################################
	["Better Caves"."Underground Generation"]

		###########################################################################################################
		## 设置洞穴的相关参数
		###########################################################################################################
		["Better Caves"."Underground Generation".Caves]
			# 设置洞穴在目标维度能够生成洞穴的百分比概率。
			# 默认：洞穴会在目标维度100%生成。
			# 范围：0.0 ~ 100.0
			"Cave Spawn Chance" = 100.0
			# 设置洞穴大小。
			# 设置单个洞穴的整体规模大小。
			# 可用选项：Small、Medium、Large、ExtraLarge、Custom  （小型、中型、大型、超大型、自定义）
			# 默认：Small（推荐）
			"Cave Region Size" = "Small"
			# 自定义设置洞穴大小，数值越小洞穴越大。
			#     只有将“Cave Region Size”设置为“Custom”时才会生效。
			#     参考数值：
			#         小型：0.008
			#         中型：0.005
			#         大型：0.0032
			#         超大型：0.001
			# 默认：0.008
			# 范围：0.0 ~ 0.05000000074505806
			"Cave Region Size Custom Value" = 0.00800000037997961

			###########################################################################################################
			## 设置1号类型洞穴，1号类型洞穴的形状类似蚯蚓
			###########################################################################################################
			["Better Caves"."Underground Generation".Caves."Type 1 Caves"]
				# 1号类型洞穴生成所需的最低Y轴坐标。
				# 默认：1
				# 范围：0 ~ 255
				"Type 1 Cave Minimum Altitude" = 1
				# 1号类型洞穴生成所需的最高Y轴坐标。
				# 默认：80
				# 范围：0 ~ 255
				"Type 1 Cave Maximum Altitude" = 80
				# 设置从地表延伸到地底时会让洞穴封闭所需的深度。
				# 如果数值太低的话则会使用的是洞穴的最大高度而不是地表高度。
				# 如果开启了覆盖地表检测的话，那么会始终使用洞穴的最大高度。
				# 默认：15（推荐）
				# 范围：0 ~ 255
				"Type 1 Cave Surface Cutoff Depth" = 15
				# 设置洞穴的垂直延伸高度，数值越低洞穴越高。
				# 默认：5.0（推荐）
				# 范围：0.0 ~ 100.0
				"Compression - Vertical" = 5.0
				# 设置洞穴的水平延伸高度，数值越低洞穴越款。
				# 默认：1.6（推荐）
				# 范围：0.0 ~ 100.0
				"Compression - Horizontal" = 1.6
				# 设置1号类型洞穴的生成概率。0 = 禁止生成。
				# 默认：10
				# 范围：0 ~ 10
				"Type 1 Cave Priority" = 10

			###########################################################################################################
			## 设置2号类型洞穴，2号类型洞穴更宽且更大
			###########################################################################################################
			["Better Caves"."Underground Generation".Caves."Type 2 Caves"]
				# 2号类型洞穴生成所需的最低Y轴坐标。
				# 默认：1
				# 范围：0 ~ 255
				"Type 2 Cave Minimum Altitude" = 1
				# 2号类型洞穴生成所需的最高Y轴坐标。
				# 默认：80
				# 范围：0 ~ 255
				"Type 2 Cave Maximum Altitude" = 80
				# 设置从地表延伸到地底时会让2号类型洞穴封闭所需的深度。
				# 如果数值太低的话则会使用的是洞穴的最大高度而不是地表高度。
				# 如果开启了覆盖地表检测的话，那么会始终使用洞穴的最大高度。
				# 默认：15（推荐）
				# 范围：0 ~ 255
				"Type 2 Cave Surface Cutoff Depth" = 15
				# 设置洞穴的垂直延伸高度，数值越低洞穴越高。
				# 默认：2.2（推荐）
				# 范围：0.0 ~ 100.0
				"Compression - Vertical" = 2.2
				# 设置洞穴的水平延伸高度，数值越低洞穴越宽。
				# 默认：0.9（推荐）
				# 范围：0.0 ~ 100.0
				"Compression - Horizontal" = 0.9
				# 设置2号类型洞穴的生成概率。0 = 禁止生成。
				# 默认：5
				# 范围：0 ~ 10
				"Type 2 Cave Priority" = 5

			###########################################################################################################
			## 设置在地表生成原版洞穴的相关参数
			###########################################################################################################
			["Better Caves"."Underground Generation".Caves."Surface Caves"]
				# 如果设置为“true”，那么在地表会生成类似原版洞穴的入口，开启的话会让洞穴的入口会更加自然且美观。
				# 默认：true
				"Enable Surface Caves" = true
				# 地表洞穴生成所需的最低Y轴坐标。
				# 默认：40
				# 范围：0 ~ 255
				"Surface Cave Minimum Altitude" = 40
				# 地表洞穴生成所需的最高Y轴坐标。
				# 默认：128
				# 范围：0 ~ 255
				"Surface Cave Maximum Altitude" = 128
				# 设置地表生成洞穴的密度，数值越高洞穴越多，并且数值越高会让地表在生成洞穴时更加紧凑。 
				# 默认：17
				# 范围：0 ~ 100
				"Surface Cave Density" = 17

			###########################################################################################################
			## 设置原版mc洞穴的相关参数
			###########################################################################################################
			["Better Caves"."Underground Generation".Caves."Vanilla Caves"]
				# 原版洞穴生成所需的最低Y轴坐标。
				# 默认：8
				# 范围：0 ~ 255
				"Vanilla Cave Minimum Altitude" = 8
				# 原版洞穴生成所需的最高Y轴坐标。
				# 默认：128
				# 范围：0 ~ 255
				"Vanilla Cave Maximum Altitude" = 128
				# 设置原版洞穴的密度，数值越高生成的洞穴越多。 
				# 默认：14（在我的世界原版中使用的值）
				# 范围：0 ~ 100
				"Vanilla Cave Density" = 14
				# 设置原版洞穴的生成概率，0 = 禁止生成。
				# 默认：0
				# 范围：0 ~ 10
				"Vanilla Cave Priority" = 0

		###########################################################################################################
		## 设置岩洞的相关参数，岩洞主要生成在较低的坐标上的较宽洞穴。
		###########################################################################################################
		["Better Caves"."Underground Generation".Caverns]
			# 设置岩洞在特定区域的生成概率。
			# 默认：岩洞有25%的概率在特定区域生成。
			# 范围：0.0 ~ 100.0
			"Cavern Spawn Chance" = 25.0
			# 设置岩洞的大小，决定了该岩洞的整体大小。
			# 可用选项：Small、Medium、Large、ExtraLarge、Custom  （小型、中型、大型、超大型、自定义）
			# 默认：Small（推荐）
			"Cavern Region Size" = "Small"
			# 自定义设置岩洞大小，数值越小洞穴越大。
			#     只有将“Cavern Region Size”设置为“Custom”时才会生效。
			#     参考数值：
			#         小型：0.008
			#         中型：0.005
			#         大型：0.0032
			#         超大型：0.001
			# 默认：0.01
			# 范围：0.0 ~ 0.05
			"Cavern Region Size Custom Value" = 0.01

			###########################################################################################################
			## 设置在较低坐标上生成含液体洞穴的相关参数
			## 液体洞穴主要是由水和熔岩组成
			###########################################################################################################
			["Better Caves"."Underground Generation".Caverns."Liquid Caverns"]
				# 液体洞穴生成所需的最低Y轴坐标。
				# 默认：1
				# 范围：0 ~ 255
				"Liquid Cavern Minimum Altitude" = 1
				# 液体洞穴生成所需的最高Y轴坐标。
				# 如果该数值高于地表，那么液体洞穴将不会生成。
				# 默认：35
				# 范围：0 ~ 255
				"Liquid Cavern Maximum Altitude" = 35
				# 设置纵向拉伸参数，数值越低液体洞穴越大。
				# 默认：1.3
				# 范围：0.0 ~ 100.0
				"Compression - Vertical" = 1.3
				# 设置水平拉伸参数，数值越低液体洞穴越大。
				# 默认：0.7
				# 范围：0.0 ~ 100.0
				"Compression - Horizontal" = 0.7
				# 设置液体洞穴的生成概率，0 = 禁止生成。
				# 默认：10
				# 范围：0 ~ 10
				"Liquid Cavern Priority" = 10

			###########################################################################################################
			## 设置在较低坐标上生成含地底洞穴的相关参数
			## 在地底洞穴里拥有更大的行走空间
			###########################################################################################################
			["Better Caves"."Underground Generation".Caverns."Floored Caverns"]
				# 地底洞穴生成所需的最低Y轴坐标。
				# 默认：1
				# 范围：0 ~ 255
				"Floored Cavern Minimum Altitude" = 1
				# 地底洞穴生成所需的最高Y轴坐标。
				# 如果该数值高于地表，那么地底洞穴将不会生成。
				# 默认：35
				# 范围：0 ~ 255
				"Floored Cavern Maximum Altitude" = 35
				# 设置纵向拉伸参数，数值越低地底洞穴越大。
				# 默认：1.3
				# 范围：0.0 ~ 100.0
				"Compression - Vertical" = 1.3
				# 设置水平拉伸参数，数值越低地底洞穴越大。
				# 默认：0.7
				# 范围：0.0 ~ 100.0
				"Compression - Horizontal" = 0.7
				# 设置地底洞穴的生成概率，0 = 禁止生成。
				# 默认：10
				# 范围：0 ~ 10
				"Floored Cavern Priority" = 10

		###########################################################################################################
		## 设置水域的相关参数
		###########################################################################################################
		["Better Caves"."Underground Generation"."Water Regions"]
			# 设置在较低坐标上生成水域而不是熔岩的概率。
			# 默认：40%
			# 范围：0.0 ~ 100.0
			"Water Region Spawn Chance" = 40.0
			# 设置水域的大小。
			# 可用选项：Small、Medium、Large、ExtraLarge、Custom  （小型、中型、大型、超大型、自定义）
			# 默认：Medium（推荐）
			"Water Region Size" = "Medium"
			# 设置水域大小的自定义数值，数值越低水域越大。
			#     只有将“Water Region Size”设置为“Custom”时才会生效。
			#     参考数值：
			#         小型：0.008
			#         中型：0.005
			#         大型：0.0032
			#         超大型：0.001
			# 默认：0.004
			# 范围：0.0 ~ 0.05
			"Water Region Size Custom Value" = 0.004

		###########################################################################################################
		## 设置峡谷的相关参数
		###########################################################################################################
		["Better Caves"."Underground Generation".Ravines]
			# 是否开启峡谷的生成。
			# 默认：true
			"Enable Ravines" = true
			# 如果设置为“true”，那么在海洋的生物群系中会生成被水淹没的峡谷。
			# 默认：true
			"Enable Flooded Ravines" = true

		###########################################################################################################
		## 设置洞穴和岩洞的拓展参数
		###########################################################################################################
		["Better Caves"."Underground Generation".Miscellaneous]
			# 设置熔岩和水域会生成的Y轴坐标。
			# 默认：10
			# 范围：0 ~ 255
			"Liquid Altitude" = 10
			# 设置在指定的Y轴高度上会生成熔岩的液体名称。
			# 如果设置的方块是无效的，则会默认生成熔岩方块。
			# 默认：minecraft:lava
			"Lava Block" = "minecraft:lava"
			# 当液体洞穴和岩洞中有坐标低于上述坐标，设置液体的名称。
			# 如果设置的方块是无效的，则会默认生成水源方块。
			# 默认：minecraft:water
			"Water Block" = "minecraft:water"
			# 是否使用安山岩覆盖掉在海洋底部生成的沙砾。
			# 可以防止因大片沙砾在海洋底部同时下落时造成的游戏卡顿。
			# 默认：true
			"Prevent Cascading Gravel" = true
			# 是否禁用洞穴和溶洞的地表检测，可以使洞穴在任何坐标上生成。
			# 一直生成到最大高度，在下界这种没有地面的维度上也许有用。
			# 默认：false
			"Override Surface Detection" = false
			# 如果设置为“true”，那么会在海洋底部生成被水淹没的峡谷。
			# 默认：true
			"Enable Flooded Underground" = true

	###########################################################################################################
	## 设置基岩在生成时的相关参数
	###########################################################################################################
	["Better Caves"."Bedrock Generation"]
		# 是否以超平坦一样的那种平坦基岩代替原版的那种坑坑洼洼的基岩生成方式。
		# 如果设置为“true”，那么会在所有的白名单维度中以更平坦基岩替换原版的基岩生成方式。
		# 默认：true
		"Flatten Bedrock" = true
		# 设置基岩层的厚度，只有将“Flatten Bedrock”设置为“true”时才能生效。
		# 范围：0 ~ 256
		"Bedrock Layer Width" = 1

	###########################################################################################################
	## 在正常游戏时请不要使用该选项。
	###########################################################################################################
	["Better Caves"."DEBUG Settings"]
		# 开启调试模式。可视化新建世界，只会显示洞穴和岩洞框架，除此之外不会显示任何方块，这对于直观地了解洞穴和岩洞的种类十分有用。
		#     1号类型洞穴：木板
		#     2号类型洞穴：圆石
		#     熔岩洞穴：红石块
		#     地底洞穴：金块
		#     地表洞穴：绿宝石块
		#     原版洞穴：砖块
		# 默认：false
		"Enable DEBUG Visualizer" = false

