
["YUNG's Better Mineshafts"]
	# 是否禁止原版废弃矿井的生成。
	# 默认：true
	"Disable Vanilla Mineshafts" = true
	# 矿井生成的最地Y坐标。
	# 默认：-55
	"Minimum y-coordinate" = -55
	# 矿井生成的最高Y坐标。
	# 默认：30
	#
	"Maximum y-coordinate" = 30

	###########################################################################################################
	## 矿床设置（注意：设置概率时请设置完成后将下面所有矿床的概率加起来算总和，如果概率总和大于或小于100那么该设置都会都无法加载并且有可能会出现BUG。）
	###########################################################################################################
	["YUNG's Better Mineshafts"."Ore Deposits"]
		"Enable Ore Deposits" = true
		# 生成仅拥有圆石的矿床概率。
		# 默认：50
		# 范围：0 ~ 100
		"Cobble Spawn Chance (Empty Deposit)" = 50
		# 生成拥有煤矿的矿床概率。
		# 默认：20
		# 范围：0 ~ 100
		"Coal Spawn Chance" = 20
		# 生成拥有铁矿的矿床概率。
		# 默认：9
		# 范围：0 ~ 100
		"Iron Spawn Chance" = 9
		# 生成拥有红石矿的矿床概率。
		# 默认：7
		# 范围：0 ~ 100
		"Redstone Spawn Chance" = 7
		# 生成拥有金矿的矿床概率。
		# 默认：7
		# 范围：0 ~ 100
		"Gold Spawn Chance" = 7
		# 生成拥有青金石矿的矿床概率。
		# 默认：3
		# 范围：0 ~ 100
		"Lapis Spawn Chance" = 3
		# 生成拥有绿宝石矿的矿床概率。
		# 默认：3
		# 范围：0 ~ 100
		"Emerald Spawn Chance" = 3
		# 生成拥有钻石矿的矿床概率。
		# 默认：1
		# 范围：0 ~ 100
		"Diamond Spawn Chance" = 1

	###########################################################################################################
	## 设置矿井里的内容生成和装饰方块的生成。
	###########################################################################################################
	["YUNG's Better Mineshafts"."Spawn Rates & More"]
		# 设置在主矿井里灯笼的生成概率。
		# 默认：.0067
		# 范围：0.0 ~ 1.0
		"Lantern Spawn Rate" = 0.0067
		# 设置在小型矿井里火把的生成概率。
		# 默认：.02
		# 范围：0.0 ~ 1.0
		"Torch Spawn Rate" = 0.02
		# 设置位于主矿井侧边工作台的生成概率。
		# 默认：.025
		# 范围：0.0 ~ 1.0
		"Workstation Spawn Rate" = 0.025
		# 设置位于主矿井侧边地窖里的工作台生成概率。
		# 默认：.25
		# 范围：0.0 ~ 1.0
		"Workstation Cellar Spawn Rate" = 0.25
		# 设置在主矿井旁生成小型矿井的概率。
		# 默认：.07
		# 范围：0.0 ~ 1.0
		"Small Shaft Spawn Rate" = 0.07
		# 设置蜘蛛网在矿井里的生成概率。
		# 默认：.15
		# 范围：0.0 ~ 1.0
		"Cobweb Spawn Rate" = 0.15
		# 设置运输矿车在小型矿井里的生成概率。
		# 默认：.00125
		# 范围：0.0 ~ 1.0
		"Small Shaft Chest Minecart Spawn Rate" = 0.00125
		# 设置TNT矿车在小型矿井里的生成概率。
		# 默认：.0025
		# 范围：0.0 ~ 1.0
		"Small Shaft TNT Minecart Spawn Rate" = 0.0025
		# 设置运输矿车在主矿井里的生成概率。
		# 默认：.01
		# 范围：0.0 ~ 1.0
		"Main Shaft Chest Minecart Spawn Rate" = 0.01
		# 设置TNT矿车在主矿井里的生成概率。
		# 默认：.0025
		# 范围：0.0 ~ 1.0
		"Main Shaft TNT Minecart Spawn Rate" = 0.0025
		# 设置被废弃的矿工休息室在小型矿井里的生成概率。
		# 默认：2
		# 范围：0 ~ 100
		"Abandoned Miners' Outpost Spawn Chance" = 2
		# 设置小型矿井的分支数量。（如：直线、拐角、梯形、交叉等）
		# 该数值决定了小型矿井的总长度。
		# 默认：9
		#
		# 范围：0 ~ 1000
		"Small Shaft Piece Chain Length" = 9

