
["YUNG's Better Desert Temples"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Desert Temples".General]
		# 是否禁止原版的沙漠神殿的生成。
		# 默认：true
		#
		"Disable Vanilla Pyramids" = true
		# 当沙漠神殿中的法老王存活时是否给予玩家挖掘疲劳。（法老王戴着特殊的头颅，很容易就可以找到）
		# 默认：true
		#
		"Apply Mining Fatigue" = true

