
["YUNG's Better Nether Fortresses"]

	###########################################################################################################
	## 常规设置
	###########################################################################################################
	["YUNG's Better Nether Fortresses".General]
		# 是否禁止原版的下界要塞的生成。
		# 默认：true
		#
		"Disable Vanilla Nether Fortresses" = true

